### ISSUE TITLE
No mobile site

### ISSUE THREAD

**Issue by domdomegg** [TechieHub/techiehub.github.io#4]
I'd reccomend you try to use your new responsive design skills (with `@media` queries) to make your site work well on mobile :)

Hopefully it helps that your navigation is all done is CSS now

**Comment by Prouser123** [comment]
Going to move the site and repo to a orginazation. see [this link](https://github.com/TechieHub/techiehub.github.io)

**Comment by domdomegg** [comment]
K cool - could you not have just [transferred ownership](https://help.github.com/articles/about-repository-transfers/)

**Comment by domdomegg** [comment]
Moved to https://github.com/TechieHub/techiehub.github.io/issues/1

**Comment by Prouser123** [comment]
Y but it would mess up stuff. I'll do it 
though if commits transfer

**Comment by Prouser123** [comment]
Transferred to org.

**Comment by Prouser123** [comment]
Working on it - https://github.com/TechieHub/techiehub.github.io/tree/mobile-dev
Not done yet though

**Comment by Prouser123** [comment]
See #5

**Comment by Prouser123** [comment]
Pull done. Closed.
